default:
  seed: 1
  output_dir: "output"
  home_dir: "../"
  dataset_dir: "../dataset"
  deterministic: False
  parallel: False
  device_id: 0
  num_workers: null
  make_dir: True

network:
  model: "segnet"
  segnet:
    input_channels: 3
    output_channels: 19  # Assuming CityScapes dataset with 19 classes

learn:
  n_epoch: 300
  batch_size: 128
  pretrained: "nontrained"
  
augment: 
  name: 
    - "base"
  hp:
    mix_p: 1.0
    cutout_p: 1.0
    cutout_size: 0.5
    patchg_p: 1.0
    patchg_size: 18
    patchg_s: 0.5

  rand:
    weight: "None"
    single: "None"
    num_op: 2
    magnitude:  9
    random_magnitude: True
    scheduled: False
    init_t: 0.0005
    fin_t: 1.0
    softmax_t: 0.5
    peak: False
    affinity: False
    save_all_affinity: False

  dynamic: True
  
dataset:
  name: "CityScapes"
  n_class: 19
  img_size: 256  # Adjust based on your CityScapes dataset
  resized_size: 256
  train_size: null

optimizer:
  name: SGD
  scheduler:
    name: cosine
    step:
      - 60
      - 120
      - 160
    
  hp:
    lr: 0.1
    lr_min: 0.0001
    lr_init_reduction: 1.0
    warmup_period: 20
    warmup_init: 1e-5
    momentum: 0.95
    weight_decay: 5e-4
    
save:
  img: True
  plot: True
  selected: True